# Generated by Django 3.0.6 on 2020-06-12 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0002_auto_20200612_1054'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='company_industry',
            field=models.TextField(blank=True),
        ),
    ]
