# Generated by Django 3.0.6 on 2020-06-13 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0003_userprofile_company_industry'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='email',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='office',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='ratings',
            field=models.IntegerField(blank=True, default='4'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userprofile',
            name='tele',
            field=models.TextField(blank=True),
        ),
    ]
