# Generated by Django 3.0.6 on 2020-06-13 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0004_auto_20200613_0945'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='budget',
            field=models.DecimalField(decimal_places=2, default='0', max_digits=12),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userprofile',
            name='target',
            field=models.DecimalField(decimal_places=2, default='0', max_digits=12),
            preserve_default=False,
        ),
    ]
