# Generated by Django 3.0.6 on 2020-06-13 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0005_auto_20200613_0832'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='contact',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='tele',
            field=models.TextField(blank=True),
        ),
    ]
