# Generated by Django 3.0.6 on 2020-06-15 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0006_auto_20200614_1000'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='achievement',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='ratings',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
