# Generated by Django 3.0.6 on 2020-06-13 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0006_auto_20200613_0833'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='ratings',
            field=models.IntegerField(blank=True, default=4),
            preserve_default=False,
        ),
    ]
