# Generated by Django 3.0.6 on 2020-05-09 10:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0002_auto_20200509_0926'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='register',
            name='companyName',
        ),
        migrations.RemoveField(
            model_name='register',
            name='country',
        ),
        migrations.RemoveField(
            model_name='register',
            name='customerName',
        ),
        migrations.RemoveField(
            model_name='register',
            name='email',
        ),
        migrations.RemoveField(
            model_name='register',
            name='password',
        ),
        migrations.RemoveField(
            model_name='register',
            name='phone',
        ),
    ]
