# Generated by Django 3.0.6 on 2020-05-17 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expense', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='created_at',
            field=models.DateTimeField(verbose_name=True),
        ),
    ]
