# Generated by Django 3.0.6 on 2020-05-16 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expense', '0002_remove_expense_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='username',
            field=models.TextField(default='darius'),
            preserve_default=False,
        ),
    ]
