# Generated by Django 3.0.6 on 2020-05-16 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expense', '0004_remove_expense_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='username',
            field=models.TextField(default='darius'),
            preserve_default=False,
        ),
    ]
