# Generated by Django 3.0.6 on 2020-06-25 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expense', '0004_auto_20200625_1359'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='expense',
            options={'ordering': ['-created_at']},
        ),
    ]
